name: Auto-TikTok
on:
  workflow_dispatch:

jobs:
  build-post:
    runs-on: ubuntu-latest

    # ← AJOUTE LE BLOC ENV ICI
    env:
      OPENAI_KEY:  ${{ secrets.OPENAI_KEY }}
      RUNWAY_KEY:  ${{ secrets.RUNWAY_KEY }}
      ELEVEN_KEY:  ${{ secrets.ELEVEN_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - name: Generate video IA
        run: python main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output.mp4
