name: Auto-TikTok
on:
  workflow_dispatch:
jobs:
  build-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Generate test video
        run: python main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output.mp4
